defaults: &defaults
  # Mailgun
  MAILGUN_API_KEY: "API Key"
  MAILGUN_DOMAIN: "Domain"
  MAILGUN_PUBLIC_KEY: "Pub key"
  MAILGUN_SMTP_LOGIN: "Default SMTP Login"
  MAILGUN_SMTP_PASSWORD: "Default Password"
  MAILGUN_SMTP_PORT: 587
  MAILGUN_SMTP_SERVER: "smtp.mailgun.org"

  # Google Auth
  PANDA_GOOGLE_KEY: "Google auth key"
  PANDA_GOOGLE_SECRET: "Google auth secret"

development:
  <<: *defaults

test:
  <<: *defaults

